### ISSUE TITLE
"Cannot read properties of null (reading 'toLocaleUpperCase')" in Playlist.tsx

### ISSUE THREAD

**Issue by ianparkinson** [mjoblin/vibinui#257]
If my CXNv2 isn't on standby when I open vibinui, it just shows a black screen with the error `Apologies, an unexpected error has occurred.`

Vibinui does start successfully if the streamer is in standby when the page is loaded. If I then take the streamer out of standby (either using vibinui or the IR remote) vibinui immediately fails with the same error. I was able to successfully turn the streamer on via vibinui without crashing the UI and play/pause the music, but I can't repro that now.

Chrome's console reports a number of variations of the same error in `Playlist.tsx`:

```
ErrorBoundary.tsx:18 vibin error TypeError: Cannot read properties of null (reading 'toLocaleUpperCase')
    at Playlist.tsx:376:87
    at Array.map (<anonymous>)
    at M5 (Playlist.tsx:373:10)
    at Oi (react-dom.production.min.js:167:137)
    at Pl (react-dom.production.min.js:197:258)
    at Oc (react-dom.production.min.js:292:88)
    at ws (react-dom.production.min.js:280:389)
    at gs (react-dom.production.min.js:280:320)
    at ys (react-dom.production.min.js:280:180)
    at ss (react-dom.production.min.js:273:245)
```

**Comment by mjoblin** [comment]
Thanks for reporting this, and for the detailed report. It looks like a missing genre field was at fault here. I've released a fix as v1.5.2. The fix should address the specific `toLocaleUpperCase()` issue you encountered, although it's plausible this might just be the first of more missing-field problems. Let me know if you encounter more.

You should be able to install the latest UI (v1.5.2) by running this on the backend: `vibin installui`.

If this only fixes the `"Apologies, an unexpected error has occurred"` problem, but vibinui is still not starting properly when the streamer is not in standby, then let me know about that too as that may be caused by a second unrelated problem.

**Comment by ianparkinson** [comment]
Thanks for the quick fix! It's working very well now.

As general feedback after a couple of minutes with it - it's really, really good, thank you for putting it together. I mostly use a streaming service, Qobuz, and I don't think I can select albums etc. from that source. But the playlist renders well (with image art and everything) and I can select a track to play from the playlist, reorder tracks, pause and play etc.

**Comment by mjoblin** [comment]
Great to hear it's working for you now, and thanks for the feedback! I appreciate it. And you're right about Qobuz -- album/etc selection is only available for local media not from streaming services.

Given your usage, you might find another StreamMagic app I released to be useful: [PunyTunes](https://punytunes.app) (https://punytunes.app). PunyTunes is a system tray app which talks directly to the streamer and doesn't use the vibin backend at all, so it's a little easier to get running -- although it doesn't support many of vibin's "bonus" features (like local media browsing, lyrics, waveforms, playlist reordering, etc).
